version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db-mysql
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: db-phpmyadmin
    environment:
      - PMA_ARBITRARY
      - PMA_HOST
      - PMA_USER
      - PMA_PASSWORD
    links:
      - db
    ports:
      - 3000:80
    volumes:
      - ./phpmyadmin/sessions:/sessions

  wordpress:
     depends_on:
       - db
     image: wordpress:latest
     container_name: wordpress
     volumes:
      - "./wp-content:/var/www/html/wp-content"
     ports:
       - "8000:80"
     restart: always
     environment:
      - WORDPRESS_DB_NAME
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
volumes:
  db_data:
